# TAREA 2 

Ejercicio 2 
Resuelve el siguiente sistema de ecuaciones aplicando el método de Cramer:
2x_1 +4x_2+6x_3=18
4x_1+5x_2+6x_3=24
3x_1+x_2-2x_3=4


In [27]:
import numpy as np # primero importamos la paqueteria

In [28]:
arr_A=np.array([[2,4,6],[4,5,6],[3,1,-2]])  
arr_A

array([[ 2,  4,  6],
       [ 4,  5,  6],
       [ 3,  1, -2]])

In [29]:
arr_B=np.array([18,24,4])
arr_B

array([18, 24,  4])

In [30]:
sol=np.linalg.solve(arr_A,arr_B) # usamos la funcion de numpy
print (sol)

[ 4. -2.  3.]


Considera la siguiente lista: estados = ["Jalisco","Puebla","CDMX","Nuevo León","Oaxaca","Chiapas","Veracruz","Yucatán","Sonora", "Jalisco","Puebla","Baja California","Querétaro","CDMX"]
Realiza lo siguiente:
Ordena la lista alfabéticamente.
Elimina los elementos repetidos.
Agrega al inicio de la lista el estado "Aguascalientes".
Agrega al final de la lista el estado "Zacatecas".
Verifica si "Oaxaca" está en la lista.
Imprime la lista final y su longitud.

In [17]:
estados=["Jalisco","Puebla","CDMX","Nuevo León","Oaxaca","Chiapas","Veracruz","Yucatán","Sonora", "Jalisco","Puebla","Baja California","Querétaro","CDMX"]

In [18]:
estados.sort()

In [19]:
estados

['Baja California',
 'CDMX',
 'CDMX',
 'Chiapas',
 'Jalisco',
 'Jalisco',
 'Nuevo León',
 'Oaxaca',
 'Puebla',
 'Puebla',
 'Querétaro',
 'Sonora',
 'Veracruz',
 'Yucatán']

In [20]:
estados.remove('CDMX')
estados.remove('Jalisco')
estados.remove('Puebla')

In [21]:
estados

['Baja California',
 'CDMX',
 'Chiapas',
 'Jalisco',
 'Nuevo León',
 'Oaxaca',
 'Puebla',
 'Querétaro',
 'Sonora',
 'Veracruz',
 'Yucatán']

In [22]:
estados.insert(0,'Aguascalientes')
estados.insert(12, 'Zacatecas')

In [23]:
estados

['Aguascalientes',
 'Baja California',
 'CDMX',
 'Chiapas',
 'Jalisco',
 'Nuevo León',
 'Oaxaca',
 'Puebla',
 'Querétaro',
 'Sonora',
 'Veracruz',
 'Yucatán',
 'Zacatecas']

In [24]:
len(estados)

13

Importa NumPy y considera los siguientes vectores:

u = np.array([2, 4, 6]) v = np.array([1, 3, 5])

Escribe un programa que haga lo siguiente:

Defina una función llamada distancia(u, v) que regrese la distancia euclidiana entre dos vectores.

Defina una función llamada normalizar(x) que regrese el vector normalizado.

Calcule el producto escalar entre u y v usando np.dot().

Calcule la norma de u y la norma de v.

Imprima:

La distancia entre u y v.
El vector u normalizado.
El vector v normalizado.
El producto escalar.

In [33]:
import numpy as np

In [34]:
u=np.array([2, 4, 6])
v=np.array([1, 3, 5])

In [42]:
normalizacion_u=u /np.linalg.norm(u)
normalizacion_v=v /np.linalg.norm(v)
producto_escalar = np.dot(u,v)
norma_u=np.linalg.norm(u)
norma_v=np.linalg.norm(v)
distancia= np.linalg.norm(u - v)

print('Distancia entre u y v:',distancia)
print('El vector u normalizado:',normalizacion_u)
print('El vector v normalizado:',normalizacion_v)
print('El producto escalar:', producto_escalar)

Distancia entre u y v: 1.7320508075688772
El vector u normalizado: [0.26726124 0.53452248 0.80178373]
El vector v normalizado: [0.16903085 0.50709255 0.84515425]
El producto escalar: 44
